### ISSUE TITLE
Fix AppVeyor Build

### ISSUE THREAD

**Issue by gep13** [cake-build/cake-vs#100]
I thought all that was required was to skip verification for the MagicChunks addin, but looks like there is more to it:

![image](https://user-images.githubusercontent.com/1271146/54615330-26f9fa80-4a1b-11e9-91b5-5a63feba2e44.png)

https://ci.appveyor.com/project/cakebuild/cake-vs/builds/23192248

**Comment by agc93** [comment]
I just did a rebuild and it seems to have worked this time, maybe just a network problem or something. LGTM now.

**Comment by gep13** [comment]
@agc93 perfect.  Let's put it down to a glitch in the matrix 😄
