### ISSUE TITLE
Support Visual Studio 2019

### ISSUE THREAD

**Issue by Lolle2000la** [cake-build/cake-vs#106]
Currently the extension only supports Visual Studio 2015 and 2017. Support for Visual Studio 2019 would be really helpful.

**Comment by gep13** [comment]
@Lolle2000la thanks for raising this issue.  This has actually already been addressed in this issue:

https://github.com/cake-build/cake-vs/issues/98

**Comment by gep13** [comment]
@Lolle2000la see this blog post for how to take the pre-release version for a spin:

https://cakebuild.net/blog/2016/12/cake-vs-prerelease

**Comment by Lolle2000la** [comment]
Thank you! Did not see that. Worked like a charm!

**Comment by Kirya522** [comment]
this thing doesn't work in last vs19 version

**Comment by ravensorb** [comment]
Any updates?

**Comment by soroshsabz** [comment]
@gep13 Why this issue is close when we do not see any stable version of cake for visual studio 2019?

thanks :)

**Comment by rroman81** [comment]
@soroshsabz this cake extension is still in pre-release phase.

**Comment by soroshsabz** [comment]
@rroman81  Please reopen this issue and make stable release of cake extension for visual studio 2019
