### ISSUE TITLE
Add support for Visual Studio 2019

### ISSUE THREAD

**Issue by Kirya522** [cake-build/cake-vs#110]
I have added custom vsix galleries for my vs
![image](https://user-images.githubusercontent.com/33904040/63148527-e67ac900-c01a-11e9-8610-14b3098fbd96.png)
But I can't receive update for my studio
![image](https://user-images.githubusercontent.com/33904040/63148557-ff837a00-c01a-11e9-990e-04f8167cfc92.png)

**Comment by marcinsmialek** [comment]
Can you try a fresh install from the https link?
It worked fine on my 16.3.0

**Comment by soroshsabz** [comment]
ITNOA

When cake official release for visual studio 2019

https://marketplace.visualstudio.com/items?itemName=vs-publisher-1392591.CakeforVisualStudio

says only support 2017

**Comment by lobster2012-user** [comment]
vs 16.2.5

![изображение](https://user-images.githubusercontent.com/9452368/71821407-22362e00-30a3-11ea-9e40-8b573e28f391.png)


![изображение](https://user-images.githubusercontent.com/9452368/71821375-0b8fd700-30a3-11ea-9789-2b14031f0922.png)

**Comment by soroshsabz** [comment]
@lobster2012-user why not release in official repo?

**Comment by ByteDev** [comment]
lobster2012-user way of adding also works for 16.4.3.

Agree with soroshsabz why not official release for vs 2019.

**Comment by soroshsabz** [comment]
Any update? Can we help you for resolve any problem that prevent to release official for visual studio 2019?

**Comment by mholo65** [comment]
> 
> 
> Any update? Can we help you for resolve any problem that prevent to release official for visual studio 2019?
> 
> @gep13 @mholo65

Ping @agc93 as he is currently working on support for VS2019.

**Comment by mediabuff** [comment]
the following link is dead.
https://www.myget.org/F/cake.vsix

**Comment by augustoproiete** [comment]
@mediabuff You have a "." (dot) in your URL that should be a "/" (forward slash).

The correct URL is **https://www.myget.org/F/cake/vsix**

![image](https://user-images.githubusercontent.com/177608/101795970-d8d63600-3ade-11eb-90ce-c8989dc5a91d.png)

![image](https://user-images.githubusercontent.com/177608/101795982-dc69bd00-3ade-11eb-91ae-d67c2939df9b.png)

**Comment by gep13** [comment]
@augustoproiete thanks for following up here, appreciate it.

@mediabuff Getting this extension updated is the next thing on my priority list.  Getting it updated to get the build working, and then going to try to get something shipped.

**Comment by gep13** [comment]
I have been testing this out, and from what I can see, Visual Studio 2019 support is working as expected, and will be included in the next release.

**Comment by soroshsabz** [comment]
Thanks for it :)
