### ISSUE TITLE
Cake for visual studio extension - not installable in VS2019 Community Edition

### ISSUE THREAD

**Issue by mediabuff** [cake-build/cake-vs#113]
![image](https://user-images.githubusercontent.com/5080114/101710630-df719880-3a5f-11eb-9bb0-30dc45b47fde.png)

**Comment by pascalberger** [comment]
This is probably a duplicate of #110

**Comment by gep13** [comment]
@mediabuff as @pascalberger this is a duplicate of an existing request.  As such, I am going to close this out, in favour of the existing issue.
