### ISSUE TITLE
Update Build Script

### ISSUE THREAD

**Issue by gep13** [cake-build/cake-vs#18]
To include things like:
- [x] GitReleaseManager for generating release notes
- [x] GitVersion for asserting Semantic Version number, including updating of required files
- [x] Push develop version of VSIX to MyGet

**NOTE:** This is not an exhaustive list, just things I am thinking about as I type.

**Comment by agc93** [comment]
Any news on getting MyGet VSIX stuff set up? I've started upgrading the build scripts to be closer to what `cake-build/cake`, `cake-build/cake-vso` etc use, but I'm leaving the "Publish" step as an AppVeyor upload for now

**Comment by gep13** [comment]
@agc93 the MyGet feed is ready to go. I will get you the information later today.
