### ISSUE TITLE
Icon in Dark Theme seems to have colours inverted

### ISSUE THREAD

**Issue by gep13** [cake-build/cake-vs#2]
As we discussed, this is what I am seeing in the dark theme:

![image](https://cloud.githubusercontent.com/assets/1271146/18413323/58868572-779c-11e6-97b4-38fee67f64d5.png)

Seems ok in here though:

![image](https://cloud.githubusercontent.com/assets/1271146/18413332/9cbb2d56-779c-11e6-9867-0258caf067fa.png)

**Comment by agc93** [comment]
Resolved! :cake: 

![screenshot 77](https://cloud.githubusercontent.com/assets/1369269/18414939/6f8438d4-7821-11e6-9f88-ec3f31325506.png)
![screenshot 78](https://cloud.githubusercontent.com/assets/1369269/18414940/754f97cc-7821-11e6-894a-fc715bebd497.png)

**Comment by gep13** [comment]
Sweet!

**Comment by agc93** [comment]
The icons from the Build > Cake Build menu were affected by the same issue, but weren't fixed at the same time, so this is still outstanding for those icons
