### ISSUE TITLE
The extension doesn't support the -experimental flag

### ISSUE THREAD

**Issue by thomaslevesque** [cake-build/cake-vs#29]
I use the `-experimental` flag to enable C# 6 features. Apparently the extension doesn't provide a way to pass this flag to cake.exe, so my Cake tasks fail to compile.

**Comment by agc93** [comment]
I'll take a look at this, and I should be able to add it alongside the other options

**Comment by thomaslevesque** [comment]
btw, I was wondering: why do I still need "experimental" to use C# 6 features? C# 6 has been out for more than a year. I thought it was because the Roslyn scripting APIs weren't yet stable, but now they are...

**Comment by patriksvensson** [comment]
We still target .NET 4.5 and that is using the older Roslyn bits. The experimental bits are not even the latest either but pre-release bits (but still a lot newer).

If you truly want the latest Roslyn bits, then you should use the Cake.CoreCLR package that contains cross platform Roslyn.

**Comment by thomaslevesque** [comment]
Ah, thanks. I'll give it a try.

**Comment by matkoch** [comment]
Is it possible to release this fix before all other issues for this milestone are resolved? Things like auto-indention, drag&drop and auto debug can be easily workarounded. But with this feature missing, I am forced to write new, soon to be changed code. #37 falls into the same category.

**Comment by agc93** [comment]
@matkoch If you look at the PR for this issue, you can check out the [AppVeyor build](https://ci.appveyor.com/project/cakebuild/cake-vs/build/1.0.37/artifacts) and you can download the VSIX directly from the build artifacts to locally install to get this fix right away.

We're working on getting a CI build available using MyGet (you can track that over at #18/#48 ), but for now each PR builds a VSIX you can use to get the latest changes.
