### ISSUE TITLE
Make the task detection independent of build.cake position

### ISSUE THREAD

**Issue by pitermarx** [cake-build/cake-vs#30]
It seems to me that build.cake cannot be on a sibiling path of the solution, but only on a parent path.

With
\git\MyProject\src\MySolution.sln
\git\MyProject\BuildScripts\build.cake
The tasks are not detected

When i moved to
\git\MyProject\build.cake
it was detected

**Comment by gep13** [comment]
Conversation where this was discussed: https://gitter.im/Microsoft/extendvs?at=57f52e3729403a416fcb7cbe

**Comment by pitermarx** [comment]
I understand. That's sad though.
As far as I am concerned, you can close this when 0.2.0 is released

**Comment by nnyegaard** [comment]
It seems that the task runner can't detect the task in the cake file even though it is in root.

I have a ASP.NET Core app with paths:
root\src
root\test
root\Api.sln
\root\cake.build

And the task runner detects the cake file, but it does not show any tasks

**Comment by gep13** [comment]
@nnyegaard is this a public repo that we can take a look at?  If so, where is it?

Also, is that a typo in your comment?  You have `cake.build` rather than `build.cake`.

**Comment by nnyegaard** [comment]
Yes sorry build.cake.

I have published the repo here: [https://github.com/nnyegaard/cakebuild](https://github.com/nnyegaard/cakebuild)

**Comment by agc93** [comment]
@nnyegaard I can see the tasks showing up when I open that repo. For the tasks to be loaded, you either a) need to have run the bootstrapper at least once or b) have Cake.exe available on your PATH. 

Do you have your tools/addins installed in a custom directory for that solution?

![screenshot 85](https://cloud.githubusercontent.com/assets/1369269/19305199/3a60c30c-90b3-11e6-8365-452998f4eb0a.png)

**Comment by nnyegaard** [comment]
I had yet to run the bootstrapper (build.ps1), but after I got the tasks. 

Thanks a lot guys!

**Comment by gep13** [comment]
I have just read through the discussion here, and I believe that this issue can now be closed.

If this isn't the case, then please comment again.
