### ISSUE TITLE
Respect C# Editor Preferences

### ISSUE THREAD

**Issue by mgasparel** [cake-build/cake-vs#39]
When in a .cake file, hitting tab does not insert spaces, even though this is how my C# text editor is configured. I can't seem to find any way to configure the cake extension independently.

![image](https://cloud.githubusercontent.com/assets/2152222/19011682/e45db8fc-876b-11e6-9701-c707b625d345.png)

**Comment by agc93** [comment]
Cake scripts (when using this extension) actually register with Visual Studio as generic code files (not C#)<sup>1</sup>, so it will use the generic editor settings by default. Have you tried setting the option in Text Editor -> **Plain Text** -> Tabs and see if that works the way you expect?

---
<sup>1</sup>: Registering a file type (such as Cake scripts) as C# in Visual Studio automatically triggers the C# compiler so your whole script will get marked as errors etc.

**Comment by mgasparel** [comment]
That's perfect. Thanks for the information!

**Comment by agc93** [comment]
No problem. Let us know if you have any other issues!
