### ISSUE TITLE
"Clean" and "Default" are only listed tasks in Task Runner Explorer

### ISSUE THREAD

**Issue by gregfiske** [cake-build/cake-vs#43]
I've run the bootstrapper.  And those tasks are the only ones from my file that appear. I downloaded the [example repo](https://github.com/cake-build/example) and all it shows is "Build" "Clean" and "Default" even though there is also "Restore-Nuget-Packages" and "Run-Unit-Tests." Am I missing something or did I misunderstand how it works?

**Comment by gep13** [comment]
@gregfiske fairly sure this has been addressed here: https://github.com/cake-build/cake-vs/issues/37 and will ship with the next release.
