### ISSUE TITLE
Add VS Options/Text Editor/Cake node

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake-vs#47]
Right now if I want to control tab and space behavior I need to use the VS Options/Text Editor/Plain Text node, but I would really like to maintain different settings between plain text and .cake files.

**Comment by gep13** [comment]
Isn't that where something like EditorConfig would come into play?

**Comment by jnm2** [comment]
I'm not familiar with EditorConfig but I don't want to have to use a 3rd party tool in addition to the Cake VS extension. From what I see EditorConfig is more about syncing IDEs which I don't need.

**Comment by agc93** [comment]
![screenshot 77](https://cloud.githubusercontent.com/assets/1369269/20354308/74022b92-ac69-11e6-8bc1-ead509f860ad.png)

This will be merged in once #44 goes in and I can re-test.

**Comment by jnm2** [comment]
@agc93 You're the best!
