### ISSUE TITLE
Update Cake to 0.19.4

### ISSUE THREAD

**Issue by agc93** [cake-build/cake-vs#50]
This will also involve updating xUnit.NET dependencies in testing template since Cake.Testing also now depends on beta xUnit packages.

**Comment by gep13** [comment]
>@agc93 said....
dependencies in testing template since Cake.Testing also now depends on beta xUnit packages.

This was actually a mistake, and that dependency shouldn't be there.

I believe that @patriksvensson is planning on correcting that in the 0.18.0 release.

**Comment by agc93** [comment]
Ah, okay. In that case, we have a couple of options:

1. Wait until Cake 0.18.0 is released and jump forward
2. Update the addin/module templates to 0.17.0 and leave the testing templates on 0.16.1
3. Update to the beta xUnit.NET packages now in advance

Thoughts @gep13 and/or @patriksvensson ? I had a quick start on this last night and I can definitely take option 3 if we want, but I'm not sure I like the inconsistency of option 2...

**Comment by gep13** [comment]
My gut feel would be to wait until 0.18.0.  I believe that @devlead wanted to get that out sooner rather than later, and then start working on getting a few things working for the Visual Studio 2017 release and moving towards a single scripting engine.

**Comment by agc93** [comment]
Fair enough, I might also leave it for now then. Especially since Visual Studio 2017 support might not be quite so straightforward for this :laughing: 

I'll keep an eye out for 0.18.0 and pick this up again then.
