### ISSUE TITLE
"Task Runner Explorer" ignores task with name containing "-" minus sign

### ISSUE THREAD

**Issue by lucaritossa** [cake-build/cake-vs#62]
If you have defined a task name like "Run-Unit-Tests"

```C#
Task("Run-Unit-Tests")
    .IsDependentOn("Build")
    .Does(() =>
{
    MSTest("./src/**/bin/" + configuration + "/*.Tests.Unit.dll");
});
```

it will not be showed/available into "Task Runner Explorer".  

Changing the "minus" into "underscore" solve (workaround) the issue.

**Comment by agc93** [comment]
Hi @lucaritossa and thanks for the report!

What version of the extension are you currently using?

If on 0.1.x can you please try installing the prerelease version of the extension as outlined in [this blog post](http://cakebuild.net/blog/2016/12/cake-vs-prerelease) as there have been quite a few changes to the task parsing logic for 0.2.x.

Thanks!

**Comment by lucaritossa** [comment]
I confirm I'm using 0.1.1.0.
I've installed 0.2.0.33 and all it's ok!!!

Thank you!
LR
