### ISSUE TITLE
Support Visual Studio 2017

### ISSUE THREAD

**Issue by shaynevanasperen** [cake-build/cake-vs#63]
Please add support for Visual Studio 2017

**Comment by agc93** [comment]
Thanks for the feedback @shaynevanasperen ! It's definitely on our roadmap, we just need to do some more testing to ensure we get the new installation and VSIX format correct.

**Comment by nvivo** [comment]
Hi, sorry to ask again, but is this still being developed?

**Comment by gep13** [comment]
@nvivo this is on my cards to get something shipped.  I am hoping to do it this week.  Got a few things off my todo list this weekend, and this and the cake-vscode extension is next on my list.

**Comment by agc93** [comment]
@gep13 In case you get to it before I do: I've had another proper crack at the features currently in `develop` and they all look good enough to merge, but most of my WIP features are too far from ready to delay any further for, so a basic `develop` merge-and-release should be ready to go for whichever of us gets there first 😄

**Comment by gep13** [comment]
@agc93 perfect, I will keep you posted if I get to this :+1:

**Comment by crash-dive** [comment]
I just wanted to add we have been using the pre-release version on VS17 for over 6 months across a team of 5 with no issues. I have just installed the latest prerelease version (https://ci.appveyor.com/project/cakebuild/cake-vs/build/0.2.0-unstable.54.build.94/artifacts) and it all seems to work fine.

Looking forward to an easier setup for new dev environments!

**Comment by gep13** [comment]
@agc93 so looks like I got to this first 😄 

Let me know if you see any issues, and let me know what you think of this:

https://github.com/cake-build/processes/blob/master/cake-vs/release.md
