### ISSUE TITLE
Publish of Extension with Support for Visual Studio 2017

### ISSUE THREAD

**Issue by martpendle** [cake-build/cake-vs#71]
Hi

I have noticed that PR #67 has been merged into the develop branch.

When will this make its way over to the main branch/be published to visual studio gallery so the extension can be downloaded in Visual Studio 2017?

Thanks

**Comment by agc93** [comment]
Hey @martpendle! So the update for 2017 support meant quite a few changes that are not always trivial to test, so I'll need to put it through it's paces first. There's also a few other features we're hoping to get into the 0.2.0 release.

That being said, it's worth noting you can download the extension in Visual Studio 2017 and try it out now using our prerelease feed. Check out [this blog post](http://cakebuild.net/blog/2016/12/cake-vs-prerelease) for info on using that to get early access to new features like this.

Hope that clears it up.

**Comment by martpendle** [comment]
Excellent! Thanks. is there anywhere I can view the release schedule?

**Comment by agc93** [comment]
Our release schedule is highly dependent on the time our team have (and in the case of this extension, especially myself), so we don't have a formalised release schedule at this time.

That being said, it's worth noting you can download the extension in Visual Studio 2017 and try it out now using our prerelease feed. Check out [this blog post](http://cakebuild.net/blog/2016/12/cake-vs-prerelease) for info on using that to get early access to new features like this.

**Comment by martpendle** [comment]
That's more than understandable, thank you for all your hard work
