### ISSUE TITLE
VS for Mac version?

### ISSUE THREAD

**Issue by alexreg** [cake-build/cake-vs#74]
This looks like a great tool. Any chance of a version for Visual Studio for Mac, in the near future?

**Comment by gep13** [comment]
@alexreg it is already in the works...

https://github.com/agc93/cake-xs

**Comment by alexreg** [comment]
Ah, brilliant!

**Comment by agc93** [comment]
@alexreg As covered in [agc93/cake-xs#2](https://github.com/agc93/cake-xs/issues/2), we're working on Mac support as part of the Xamarin Studio addin. Discussion continues there 😄
