### ISSUE TITLE
Different behavior among VS & PS BootStrapper

### ISSUE THREAD

**Issue by MonDeveloper** [cake-build/cake-vs#78]
I'm experiencing some strange behaviors, it seems CAKE perform differently when launched via PS Bootstrapper or via VS Task Runner (using the cake-vs extension).

- Sometimes it uses an old version of the roselyn compiler (no c#6) and it won't compile the script because I use string interpolation
```
Error: Roslyn.Compilers.CompilationErrorException: C:/_Sources/_TFVC/CREApp/Main/src/Libraries/Libraries.cake(44,22): error CS1525: Invalid expression term ''
Process terminated with code 1.
```
I guessed the proble is related to the version of the compiler (and the c# language def, of course) because at the position there is this string interpolation:
``` c#
	var versionSuffix = $"alpha.{versionSuffix_day}.{versionSuffix_sec}";`
```

- Sometimes it gives error about cake assemblies like this one: 
```
Error: Microsoft.CodeAnalysis.Scripting.CompilationErrorException: C:/_Sources/_TFVC/CREApp/Main/src/Master.cake(158,3): error CS0117: 'OpenCoverSettings' does not contain a definition for 'TargetDirectory'
Process terminated with code 1.
```

Anyway, the strange part is that these problems occur ONLY using the cake-vs extension and never using the PS Bootstrapper (or the cake directly via command line).
Furthermore, during some sunny day, also using the cake-vs extension it works fine, with no reason (apparently)

My build.cake it a very simple one, just a few line more than a "Hello World".
I also double checked the file encoding, it's ok.

And, I repeat, using the PS bootstrapper everything work as expected, all the times.

I'm sorry I'm so vague but I'm no more on PC (writing on mobile) and I'll be disco for a couple of weeks.

Hope someone else matched this issue and found a workaround.

**Comment by MonDeveloper** [comment]
Just adding another error that could bring more value to the analysis. Here the step to reproduce

- Take a plain build.cake working on both VS & PS
- Add **Cake.FileHelpers** addin
- Try running with VS it fails with this error:
```
C:\_Sources\_TFVC\CREApp\Main\src\Services\WFM> cake build.cake
Could not find any assemblies compatible with .NETFramework,Version=v4.5.
Error: Failed to install addin 'Cake.FileHelpers'.
Process terminated with code 1.
```
- Try running with PS it works as expected and it install the addin
``` powershell
PS C:\_Sources\_TFVC\CREApp\Main\src\Services\WFM> .\build.ps1
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
Compiling build script...

----------------------------------------
Setup
----------------------------------------
Executing custom setup action...
Running tasks...

========================================
DBG
========================================
Executing task: DBG
Finished executing task: DBG

========================================
Default
========================================
Executing task: Default
Finished executing task: Default

----------------------------------------
Teardown
----------------------------------------
Executing custom teardown action...
Finished running tasks.

Task                          Duration
--------------------------------------------------
DBG                           00:00:00.0412922
Default                       00:00:00.0039455
--------------------------------------------------
Total:                        00:00:00.0452377
```

**Comment by gep13** [comment]
Based on what was discussed here, I think the problem was that in one scenario (using the bootstrapper) addins were being added via the packages.config file, which were being resolved in the bootstrapper.  When executing the task directly, which simply runs cake.exe, those addins were not being restored.  Usage of the packages.config files for addins/tools/modules is not longer recommended, and therefore, I don't think there is additional work that is required here.

As such, I am going to go ahead and close out this issue.
