### ISSUE TITLE
Add Build Script

### ISSUE THREAD

**Issue by gep13** [cake-build/cake-vs#8]
- Ready for publishing to Marketplace
- Will be similar to what is done for VSTS and VsCode extensions

**Comment by agc93** [comment]
I actually tried this a little while ago and fails as there's a custom build action on one of the files that Cake doesn't seem to understand. I'll look into this again and see if I can get it to work.

**Comment by agc93** [comment]
@gep13 I have a script that builds and packages the VSIX to `dist/`, but am not 100% sure on how the publishing process works and the VS Code script is pretty complex.. Ideas on next steps?

**Comment by gep13** [comment]
Nice one!

Push what you have, and we can work on it together.

**Comment by agc93** [comment]
[018c9a5](https://github.com/agc93/Cake.VisualStudio/commit/018c9a5be60e75bd67ea2e96b125223d079340f9) added the basic build script that creates the package, now just need to work out the publishing etc parts

**Comment by gep13** [comment]
Last night I pushed a new version of Cake.Tfx that includes a publish step. You just need to provide the path to the vsix, and the personal access token, which will come from an environment variable, similar to the score extension.

**Comment by gep13** [comment]
**NOTE:** The Cake.Tfx extension publish command is relatively untested, so this will.be it's trial by fire. 🙂

**Comment by agc93** [comment]
Ah, I was wondering why it wasn't in the docs, but being less than 24 hours old might be why :laughing: . Okay, I'll put a new "Publish" task in there, push and get you to have a look at it before we take the plunge!

I'll just set it to some random environment variable name and we can adjust once we get to actually putting it through CI

**Comment by gep13** [comment]
Damnit! Knew there was something I had to do! Haven't updated the usage docs, but there should be an example in the xml comments for each alias. The one thing I am not sure of is how do you distinguish a visual studio extension from a vscode or vsts extension? Vscode extensions are pushed with the vsce cli, so that makes sense, but I think vsts and vs extensions are pushed with the same tfx cli.

**Comment by agc93** [comment]
@gep13 good point. Because judging by [this documentation](https://github.com/Microsoft/tfs-cli/blob/master/docs/extensions.md) for TFX itself, it looks like it only does VSTS and TFS extensions.

And if you follow the links from the main Marketplace for working with Visual Studio extensions they send you back to the "old" Gallery site to upload. I think we may have been a bit optimistic about using `tfx` for this :confounded:

**Comment by agc93** [comment]
@gep13 As discussed, I've updated the build script to just upload an AppVeyor artifact, rather than attempting to publish. Does that look/sound correct?

**Comment by agc93** [comment]
Resolved by #10
