### ISSUE TITLE
Cake for Visual Studio 0.2.0.0 crashes constantly.

### ISSUE THREAD

**Issue by devlead** [cake-build/cake-vs#84]
@PradeepLoganathan commented on [Wed Oct 25 2017](https://github.com/cake-build/cake/issues/1893)

### What You Are Seeing?
Cake extension is causing VS 2017 15.4.1 to crash constantly. It is replicable easily.

### What is Expected?
Cake extension should not crash.

### What version of Cake are you using?
Cake for Visual Studio 0.2.0.0

### Are you running on a 32 or 64 bit system?
I am running a 64 bit system.

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
None yet.

### How Did You Get This To Happen? (Steps to Reproduce)
After installing Cake for visual studio, I created a powershell bootstrapper and a cake.config file. I created a new build.cake file without any code. It crashes once this file is opened. I opened the file in notepad and it is empty.

### Output Log
I do not have any output log for the issue. Trying to check if VS2017 has a log.

---

@SIkebe commented on [Fri Oct 27 2017](https://github.com/cake-build/cake/issues/1893#issuecomment-339842438)

There is a repository of Cake extension for Visual Studio.
https://github.com/cake-build/cake-vs

You should probably raise an issue there.

---

@PradeepLoganathan commented on [Fri Oct 27 2017](https://github.com/cake-build/cake/issues/1893#issuecomment-339868253)

Will do thanks !!

**Comment by VanKrock** [comment]
CallStack from EventViewer
 System.NullReferenceException
   в Cake.VisualStudio.Helpers.Extensions.RequiresOffset(Microsoft.VisualStudio.Text.ITextSnapshotLine, System.String[])
   в Cake.VisualStudio.Editor.SmartIndent.GetDesiredIndentation(Microsoft.VisualStudio.Text.ITextSnapshotLine)
   в Microsoft.VisualStudio.Text.Editor.Implementation.SmartIndentationService.GetDesiredIndentation(Microsoft.VisualStudio.Text.Editor.ITextView, Microsoft.VisualStudio.Text.ITextSnapshotLine)
   в Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.MapXCoordinate(Microsoft.VisualStudio.Text.Formatting.ITextViewLine, Double, Boolean)
   в Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.MoveTo(Microsoft.VisualStudio.Text.Formatting.ITextViewLine, Double, Boolean)
   в Microsoft.VisualStudio.Text.Editor.Implementation.CaretElement.MoveTo(Microsoft.VisualStudio.Text.Formatting.ITextViewLine, Double)
   в Microsoft.VisualStudio.Text.Operations.Implementation.EditorOperations.MoveCaret(Microsoft.VisualStudio.Text.Formatting.ITextViewLine, Double, Boolean)
   в Microsoft.VisualStudio.Text.Editor.Implementation.MasterMouseProcessor.HandleMouseLeftButtonDown(Boolean, Boolean, System.Windows.Point)
   в Microsoft.VisualStudio.Text.Editor.Implementation.MasterMouseProcessor.DefaultMouseLeftButtonDownHandler(System.Object, System.Windows.Input.MouseButtonEventArgs)
   в Microsoft.VisualStudio.Text.Utilities.WpfMouseProcessor+<>c__DisplayClass34_0.<UIElement_MouseLeftButtonDown>b__1()
   в Microsoft.VisualStudio.Text.Utilities.WpfMouseProcessor.MouseProcessorHandler(System.Windows.RoutedEventArgs, System.Action`1<Microsoft.VisualStudio.Text.Editor.IMouseProcessor>, System.Action, System.Action`1<Microsoft.VisualStudio.Text.Editor.IMouseProcessor>)
   в Microsoft.VisualStudio.Text.Utilities.WpfMouseProcessor.UIElement_MouseLeftButtonDown(System.Object, System.Windows.Input.MouseButtonEventArgs)
   в System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   в System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   в System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   в System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   в System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   в System.Windows.UIElement.OnMouseDownThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   в System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   в System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   в System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   в System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   в System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   в System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   в System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   в System.Windows.Input.InputManager.ProcessStagingArea()
   в System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   в System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   в System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   в System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   в System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   в MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by VanKrock** [comment]
#87

**Comment by agc93** [comment]
Resolved by #87
