### ISSUE TITLE
Syntax Highlighting Broken Visual Studio 2015 - Regression Bug ?

### ISSUE THREAD

**Issue by abjoseph** [cake-build/cake-vs#88]
I'm currently using Visual Studio 2015 Update 3 and after upgrading from version 0.1.1 to anything higher I no longer get Cake DSL syntax highlighting.

Reverting back to version 0.1.1 restores the limited but much appreciated syntax highlighting.

**Comment by MarkKharitonov** [comment]
I have just installed the cake plugin and there is no syntax highlighting. This is version 0.2.0.0

I guess I need to explore installing 0.1.1 instead.

**Comment by gep13** [comment]
I am going to go ahead and close this out.  In the upcoming release of the Cake Extension for Visual Studio we are removing support for Visual Studio 2015, and when I checked in 2017 and 2019 syntax highlighting is working as expected.
