### ISSUE TITLE
Unable to add a binding to the Project Open event

### ISSUE THREAD

**Issue by mmacehardyman** [cake-build/cake-vs#97]
I am struggling to get a Cake task to work with the Project Open binding in the Visual Studio Task Runner.
It seems to be added after I try, but then instantly disappears without making any changes.
The other bindings work just fine.

Am I the only one seeing this problem, and/or is there a solution available?

Thanks.

**Comment by mmacehardyman** [comment]
@agc93 Great that it's fixed (glad it was a small fix)! When can we expect to see this in the upcoming release?

**Comment by gep13** [comment]
>@mmacehardyman said...
When can we expect to see this in the upcoming release?

Short answer... don't know.  There are a few things that we likely want to tackle in this release.  I would suggest following along on the 0.3.0 milestone to see when all items (once added to the milestone) are closed.  You should be able to use the pre-release version, once we fix up the AppVeyor build which currently isn't working.

**Comment by agc93** [comment]
Just want to update @mmacehardyman that the prerelease builds *should* be working correctly now. 

If you get a chance to [try out the prerelease builds](https://cakebuild.net/blog/2016/12/cake-vs-prerelease) and let us know if this is working now, that would be helpful!

**Comment by mmacehardyman** [comment]
Thanks @agc93 ! I tried the prerelease build and it's now working properly!
