### ISSUE TITLE
Make available for VS 2019

### ISSUE THREAD

**Issue by jakubsuchybio** [cake-build/cake-vs#98]
Hi,
could you make cake-vs extension available for VS2019?
Thanks :)

**Comment by lprichar** [comment]
Any plans to publish the plugin to the marketplace, or will it stay in myget indefinitely?

**Comment by devlead** [comment]
Yes

**Comment by martin-pritchard** [comment]
Is there an ETA for publishing?

**Comment by patriksvensson** [comment]
No. Probably as soon as someone have time to do it and look into CI etc for it

**Comment by lprichar** [comment]
Any updates on this?

**Comment by Peremoga22** [comment]
How to Customize Cake in Visual Studio 2019?

**Comment by soroshsabz** [comment]
Please reopen this issue and make stable release of cake extension for visual studio 2019
